/**
 * Static fallback conditions — used when the Google Sheet is empty or inaccessible.
 *
 * Content (intro, symptoms, "How Homeopathy Helps", expectations, FAQs, SEO meta)
 * is sourced from `data/services-content.json`, which is generated by
 * `scripts/parse-services.mjs` from `new-services.md`. Re-run that script after
 * editing the markdown to refresh the JSON.
 *
 * Only the per-slug category and icon are maintained here.
 */
import type { ConditionCategory } from './conditions';
import type {
  HealingCondition,
  ExpectationStage,
  ConditionFaq,
} from './healing-conditions';
import SERVICES_CONTENT from '@/data/services-content.json';

interface ServiceContent {
  slug: string;
  name: string;
  tagline: string;
  metaTitle: string;
  metaDescription: string;
  intro: string;
  symptoms: string[];
  howHomeopathyHelps: string;
  expectations: ExpectationStage[];
  faqs: ConditionFaq[];
}

const CONTENT = SERVICES_CONTENT as Record<string, ServiceContent>;

/** Per-slug presentation metadata: category + display icon. */
const META: Record<string, { category: ConditionCategory; icon: string }> = {
  'alopecia-hair-loss':         { category: 'Lifestyle',       icon: '🌿' },
  'cancer-supportive-care':     { category: 'Supportive Care', icon: '🕊️' },
  'joint-problems-arthritis':   { category: 'Chronic Care',    icon: '🦴' },
  'womens-health':              { category: "Women's Health",  icon: '🌸' },
  'diabetes-mellitus':          { category: 'Lifestyle',       icon: '🩸' },
  'geriatric-disorders':        { category: 'Chronic Care',    icon: '🧓' },
  'depression-anxiety':         { category: 'Chronic Care',    icon: '🧠' },
  'gastrointestinal-disorders': { category: 'Chronic Care',    icon: '🫀' },
  'pediatric-diseases':         { category: 'Pediatric',       icon: '🧒' },
  'skin-diseases':              { category: 'Skin',            icon: '✨' },
  'respiratory-diseases':       { category: 'Respiratory',     icon: '🫁' },
  'thyroid-disorders':          { category: 'Lifestyle',       icon: '🦋' },
  'autoimmune-disorders':       { category: 'Chronic Care',    icon: '🛡️' },
  'migraine':                   { category: 'Chronic Care',    icon: '🌀' },
};

function buildCondition(slug: string): HealingCondition {
  const c = CONTENT[slug];
  const m = META[slug];
  if (!c) throw new Error(`Missing services-content.json entry for slug: ${slug}`);
  return {
    slug,
    name: c.name,
    category: m.category,
    shortDesc: c.tagline,
    intro: c.intro,
    symptoms: c.symptoms,
    howHomeopathyHelps: c.howHomeopathyHelps,
    icon: m.icon,
    status: 'published',
    expectations: c.expectations,
    faqs: c.faqs,
    metaTitle: c.metaTitle,
    metaDescription: c.metaDescription,
  };
}

export const STATIC_CONDITIONS: HealingCondition[] = Object.keys(META).map(buildCondition);
